// Gerado por 06_Scripts/gerar_sessoes_tec.py - NAO editar a mao.
window.SESSOES_TEC = {
 "gerado_em": "2026-08-03T10:24:15",
 "fonte": "07_TEC/TEC_Captura/tec_registros_*.json (1 sessão por dia+assunto)",
 "sessoes": [
  {
   "uid": "TEC~2026-06-26~1",
   "origem": "tec",
   "data": "2026-06-26",
   "mat": "DFin",
   "topicId": "1",
   "assuntoLivre": "",
   "minutos": 10,
   "qResolvidas": 10,
   "qAcertadas": 9,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-06-26~25",
   "origem": "tec",
   "data": "2026-06-26",
   "mat": "CG",
   "topicId": "25",
   "assuntoLivre": "",
   "minutos": 32,
   "qResolvidas": 14,
   "qAcertadas": 11,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-06-30~100",
   "origem": "tec",
   "data": "2026-06-30",
   "mat": "DCON",
   "topicId": "100",
   "assuntoLivre": "",
   "minutos": 8,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-06-30~101",
   "origem": "tec",
   "data": "2026-06-30",
   "mat": "DCON",
   "topicId": "101",
   "assuntoLivre": "",
   "minutos": 10,
   "qResolvidas": 7,
   "qAcertadas": 5,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-06-30~64",
   "origem": "tec",
   "data": "2026-06-30",
   "mat": "AUD",
   "topicId": "64",
   "assuntoLivre": "",
   "minutos": 154,
   "qResolvidas": 31,
   "qAcertadas": 22,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-06-30~83",
   "origem": "tec",
   "data": "2026-06-30",
   "mat": "CASP",
   "topicId": "83",
   "assuntoLivre": "",
   "minutos": 38,
   "qResolvidas": 32,
   "qAcertadas": 26,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-01~sem-assunto-177bb3",
   "origem": "tec",
   "data": "2026-07-01",
   "mat": "DFin",
   "topicId": null,
   "assuntoLivre": "(sem assunto no TEC)",
   "minutos": 1,
   "qResolvidas": 2,
   "qAcertadas": 0,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-01~sem-assunto-036ef6",
   "origem": "tec",
   "data": "2026-07-01",
   "mat": "TI",
   "topicId": null,
   "assuntoLivre": "TI - Ciência de Dados e Inteligência Artificial — geral",
   "minutos": 6,
   "qResolvidas": 1,
   "qAcertadas": 0,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-01~101",
   "origem": "tec",
   "data": "2026-07-01",
   "mat": "DCON",
   "topicId": "101",
   "assuntoLivre": "",
   "minutos": 13,
   "qResolvidas": 8,
   "qAcertadas": 5,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-01~114",
   "origem": "tec",
   "data": "2026-07-01",
   "mat": "TI",
   "topicId": "114",
   "assuntoLivre": "",
   "minutos": 5,
   "qResolvidas": 5,
   "qAcertadas": 4,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-01~115",
   "origem": "tec",
   "data": "2026-07-01",
   "mat": "TI",
   "topicId": "115",
   "assuntoLivre": "",
   "minutos": 7,
   "qResolvidas": 9,
   "qAcertadas": 6,
   "obs": "reconstruída do TEC (5 assuntos)"
  },
  {
   "uid": "TEC~2026-07-01~116",
   "origem": "tec",
   "data": "2026-07-01",
   "mat": "TI",
   "topicId": "116",
   "assuntoLivre": "",
   "minutos": 2,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-01~117",
   "origem": "tec",
   "data": "2026-07-01",
   "mat": "TI",
   "topicId": "117",
   "assuntoLivre": "",
   "minutos": 4,
   "qResolvidas": 4,
   "qAcertadas": 3,
   "obs": "reconstruída do TEC (3 assuntos)"
  },
  {
   "uid": "TEC~2026-07-01~6",
   "origem": "tec",
   "data": "2026-07-01",
   "mat": "DFin",
   "topicId": "6",
   "assuntoLivre": "",
   "minutos": 29,
   "qResolvidas": 15,
   "qAcertadas": 8,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-02~emprestimos-e-fornecedores-d347b8",
   "origem": "tec",
   "data": "2026-07-02",
   "mat": "CG",
   "topicId": null,
   "assuntoLivre": "Empréstimos e Fornecedores",
   "minutos": 2,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-02~propriedades-para-investimento-cpc-28-adfa5a",
   "origem": "tec",
   "data": "2026-07-02",
   "mat": "CG",
   "topicId": null,
   "assuntoLivre": "Propriedades para Investimento (CPC 28)",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 0,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-02~reservas-de-capital-5cbdcc",
   "origem": "tec",
   "data": "2026-07-02",
   "mat": "CG",
   "topicId": null,
   "assuntoLivre": "Reservas de Capital",
   "minutos": 9,
   "qResolvidas": 1,
   "qAcertadas": 0,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-02~sem-assunto-2c6431",
   "origem": "tec",
   "data": "2026-07-02",
   "mat": "CG",
   "topicId": null,
   "assuntoLivre": "Contabilidade Geral — geral",
   "minutos": 5,
   "qResolvidas": 5,
   "qAcertadas": 3,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-02~102",
   "origem": "tec",
   "data": "2026-07-02",
   "mat": "DCON",
   "topicId": "102",
   "assuntoLivre": "",
   "minutos": 25,
   "qResolvidas": 19,
   "qAcertadas": 18,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-02~118",
   "origem": "tec",
   "data": "2026-07-02",
   "mat": "Estat",
   "topicId": "118",
   "assuntoLivre": "",
   "minutos": 33,
   "qResolvidas": 7,
   "qAcertadas": 4,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-02~46",
   "origem": "tec",
   "data": "2026-07-02",
   "mat": "DAD",
   "topicId": "46",
   "assuntoLivre": "",
   "minutos": 45,
   "qResolvidas": 31,
   "qAcertadas": 20,
   "obs": "reconstruída do TEC (7 assuntos)"
  },
  {
   "uid": "TEC~2026-07-02~47",
   "origem": "tec",
   "data": "2026-07-02",
   "mat": "DAD",
   "topicId": "47",
   "assuntoLivre": "",
   "minutos": 106,
   "qResolvidas": 12,
   "qAcertadas": 8,
   "obs": "reconstruída do TEC (6 assuntos)"
  },
  {
   "uid": "TEC~2026-07-02~65",
   "origem": "tec",
   "data": "2026-07-02",
   "mat": "AUD",
   "topicId": "65",
   "assuntoLivre": "",
   "minutos": 21,
   "qResolvidas": 31,
   "qAcertadas": 28,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-03~6",
   "origem": "tec",
   "data": "2026-07-03",
   "mat": "DFin",
   "topicId": "6",
   "assuntoLivre": "",
   "minutos": 21,
   "qResolvidas": 29,
   "qAcertadas": 22,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-03~83",
   "origem": "tec",
   "data": "2026-07-03",
   "mat": "CASP",
   "topicId": "83",
   "assuntoLivre": "",
   "minutos": 46,
   "qResolvidas": 23,
   "qAcertadas": 18,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-03~84",
   "origem": "tec",
   "data": "2026-07-03",
   "mat": "CASP",
   "topicId": "84",
   "assuntoLivre": "",
   "minutos": 135,
   "qResolvidas": 11,
   "qAcertadas": 6,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-06~3",
   "origem": "tec",
   "data": "2026-07-06",
   "mat": "DFin",
   "topicId": "3",
   "assuntoLivre": "",
   "minutos": 33,
   "qResolvidas": 27,
   "qAcertadas": 18,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-06~46",
   "origem": "tec",
   "data": "2026-07-06",
   "mat": "DAD",
   "topicId": "46",
   "assuntoLivre": "",
   "minutos": 3,
   "qResolvidas": 6,
   "qAcertadas": 6,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-06~48",
   "origem": "tec",
   "data": "2026-07-06",
   "mat": "DAD",
   "topicId": "48",
   "assuntoLivre": "",
   "minutos": 22,
   "qResolvidas": 18,
   "qAcertadas": 11,
   "obs": "reconstruída do TEC (2 assuntos)"
  },
  {
   "uid": "TEC~2026-07-06~50",
   "origem": "tec",
   "data": "2026-07-06",
   "mat": "DAD",
   "topicId": "50",
   "assuntoLivre": "",
   "minutos": 10,
   "qResolvidas": 8,
   "qAcertadas": 4,
   "obs": "reconstruída do TEC (2 assuntos)"
  },
  {
   "uid": "TEC~2026-07-07~26",
   "origem": "tec",
   "data": "2026-07-07",
   "mat": "CG",
   "topicId": "26",
   "assuntoLivre": "",
   "minutos": 24,
   "qResolvidas": 13,
   "qAcertadas": 8,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-07~27",
   "origem": "tec",
   "data": "2026-07-07",
   "mat": "CG",
   "topicId": "27",
   "assuntoLivre": "",
   "minutos": 11,
   "qResolvidas": 4,
   "qAcertadas": 3,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-07~66",
   "origem": "tec",
   "data": "2026-07-07",
   "mat": "AUD",
   "topicId": "66",
   "assuntoLivre": "",
   "minutos": 2,
   "qResolvidas": 3,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC (2 assuntos)"
  },
  {
   "uid": "TEC~2026-07-07~68",
   "origem": "tec",
   "data": "2026-07-07",
   "mat": "AUD",
   "topicId": "68",
   "assuntoLivre": "",
   "minutos": 6,
   "qResolvidas": 6,
   "qAcertadas": 5,
   "obs": "reconstruída do TEC (2 assuntos)"
  },
  {
   "uid": "TEC~2026-07-07~69",
   "origem": "tec",
   "data": "2026-07-07",
   "mat": "AUD",
   "topicId": "69",
   "assuntoLivre": "",
   "minutos": 19,
   "qResolvidas": 11,
   "qAcertadas": 6,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-07~72",
   "origem": "tec",
   "data": "2026-07-07",
   "mat": "AUD",
   "topicId": "72",
   "assuntoLivre": "",
   "minutos": 14,
   "qResolvidas": 3,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-07~80",
   "origem": "tec",
   "data": "2026-07-07",
   "mat": "AUD",
   "topicId": "80",
   "assuntoLivre": "",
   "minutos": 4,
   "qResolvidas": 5,
   "qAcertadas": 5,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-07~83",
   "origem": "tec",
   "data": "2026-07-07",
   "mat": "CASP",
   "topicId": "83",
   "assuntoLivre": "",
   "minutos": 4,
   "qResolvidas": 7,
   "qAcertadas": 6,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-07~87",
   "origem": "tec",
   "data": "2026-07-07",
   "mat": "CASP",
   "topicId": "87",
   "assuntoLivre": "",
   "minutos": 20,
   "qResolvidas": 14,
   "qAcertadas": 9,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-07~88",
   "origem": "tec",
   "data": "2026-07-07",
   "mat": "CASP",
   "topicId": "88",
   "assuntoLivre": "",
   "minutos": 8,
   "qResolvidas": 10,
   "qAcertadas": 5,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-08~1",
   "origem": "tec",
   "data": "2026-07-08",
   "mat": "DFin",
   "topicId": "1",
   "assuntoLivre": "",
   "minutos": 5,
   "qResolvidas": 6,
   "qAcertadas": 5,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-08~103",
   "origem": "tec",
   "data": "2026-07-08",
   "mat": "DCON",
   "topicId": "103",
   "assuntoLivre": "",
   "minutos": 4,
   "qResolvidas": 3,
   "qAcertadas": 2,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-08~106",
   "origem": "tec",
   "data": "2026-07-08",
   "mat": "DCON",
   "topicId": "106",
   "assuntoLivre": "",
   "minutos": 70,
   "qResolvidas": 8,
   "qAcertadas": 5,
   "obs": "reconstruída do TEC (2 assuntos)"
  },
  {
   "uid": "TEC~2026-07-08~108",
   "origem": "tec",
   "data": "2026-07-08",
   "mat": "DCON",
   "topicId": "108",
   "assuntoLivre": "",
   "minutos": 10,
   "qResolvidas": 9,
   "qAcertadas": 7,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-08~114",
   "origem": "tec",
   "data": "2026-07-08",
   "mat": "TI",
   "topicId": "114",
   "assuntoLivre": "",
   "minutos": 15,
   "qResolvidas": 20,
   "qAcertadas": 15,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-08~118",
   "origem": "tec",
   "data": "2026-07-08",
   "mat": "Estat",
   "topicId": "118",
   "assuntoLivre": "",
   "minutos": 7,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-08~119",
   "origem": "tec",
   "data": "2026-07-08",
   "mat": "Estat",
   "topicId": "119",
   "assuntoLivre": "",
   "minutos": 19,
   "qResolvidas": 6,
   "qAcertadas": 3,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-08~136",
   "origem": "tec",
   "data": "2026-07-08",
   "mat": "DCON",
   "topicId": "136",
   "assuntoLivre": "",
   "minutos": 8,
   "qResolvidas": 6,
   "qAcertadas": 5,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-08~2",
   "origem": "tec",
   "data": "2026-07-08",
   "mat": "DFin",
   "topicId": "2",
   "assuntoLivre": "",
   "minutos": 3,
   "qResolvidas": 6,
   "qAcertadas": 6,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-08~27",
   "origem": "tec",
   "data": "2026-07-08",
   "mat": "CG",
   "topicId": "27",
   "assuntoLivre": "",
   "minutos": 37,
   "qResolvidas": 23,
   "qAcertadas": 16,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-08~3",
   "origem": "tec",
   "data": "2026-07-08",
   "mat": "DFin",
   "topicId": "3",
   "assuntoLivre": "",
   "minutos": 22,
   "qResolvidas": 15,
   "qAcertadas": 12,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-08~4",
   "origem": "tec",
   "data": "2026-07-08",
   "mat": "DFin",
   "topicId": "4",
   "assuntoLivre": "",
   "minutos": 51,
   "qResolvidas": 20,
   "qAcertadas": 16,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-08~6",
   "origem": "tec",
   "data": "2026-07-08",
   "mat": "DFin",
   "topicId": "6",
   "assuntoLivre": "",
   "minutos": 4,
   "qResolvidas": 6,
   "qAcertadas": 3,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-09~conceito-objeto-finalidade-tecnicas-contabeis-equacao-patrim-37be13",
   "origem": "tec",
   "data": "2026-07-09",
   "mat": "CG",
   "topicId": null,
   "assuntoLivre": "Conceito, Objeto, Finalidade, Técnicas Contábeis, Equação Patrimonial",
   "minutos": 6,
   "qResolvidas": 3,
   "qAcertadas": 3,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-09~outras-questoes-e-topicos-mesclados-de-auditoria-governament-9f3651",
   "origem": "tec",
   "data": "2026-07-09",
   "mat": "AUD",
   "topicId": null,
   "assuntoLivre": "Outras Questões e Tópicos Mesclados de Auditoria Governamental",
   "minutos": 28,
   "qResolvidas": 24,
   "qAcertadas": 19,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-09~passivo-exigivel-a-longo-prazo-1798a5",
   "origem": "tec",
   "data": "2026-07-09",
   "mat": "CG",
   "topicId": null,
   "assuntoLivre": "Passivo Exigível a Longo Prazo",
   "minutos": 3,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-09~sem-assunto-177bb3",
   "origem": "tec",
   "data": "2026-07-09",
   "mat": "DFin",
   "topicId": null,
   "assuntoLivre": "(sem assunto no TEC)",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 0,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-09~sem-assunto-660b27",
   "origem": "tec",
   "data": "2026-07-09",
   "mat": "AUD",
   "topicId": null,
   "assuntoLivre": "Auditoria Governamental e Controle — geral",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-09~sem-assunto-2c6431",
   "origem": "tec",
   "data": "2026-07-09",
   "mat": "CG",
   "topicId": null,
   "assuntoLivre": "Contabilidade Geral — geral",
   "minutos": 10,
   "qResolvidas": 6,
   "qAcertadas": 4,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-09~104",
   "origem": "tec",
   "data": "2026-07-09",
   "mat": "DCON",
   "topicId": "104",
   "assuntoLivre": "",
   "minutos": 31,
   "qResolvidas": 18,
   "qAcertadas": 16,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-09~119",
   "origem": "tec",
   "data": "2026-07-09",
   "mat": "Estat",
   "topicId": "119",
   "assuntoLivre": "",
   "minutos": 7,
   "qResolvidas": 2,
   "qAcertadas": 2,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-09~26",
   "origem": "tec",
   "data": "2026-07-09",
   "mat": "CG",
   "topicId": "26",
   "assuntoLivre": "",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-09~27",
   "origem": "tec",
   "data": "2026-07-09",
   "mat": "CG",
   "topicId": "27",
   "assuntoLivre": "",
   "minutos": 4,
   "qResolvidas": 3,
   "qAcertadas": 3,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-09~35",
   "origem": "tec",
   "data": "2026-07-09",
   "mat": "CG",
   "topicId": "35",
   "assuntoLivre": "",
   "minutos": 2,
   "qResolvidas": 2,
   "qAcertadas": 2,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-09~37",
   "origem": "tec",
   "data": "2026-07-09",
   "mat": "CG",
   "topicId": "37",
   "assuntoLivre": "",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-09~49",
   "origem": "tec",
   "data": "2026-07-09",
   "mat": "DAD",
   "topicId": "49",
   "assuntoLivre": "",
   "minutos": 2,
   "qResolvidas": 3,
   "qAcertadas": 3,
   "obs": "reconstruída do TEC (2 assuntos)"
  },
  {
   "uid": "TEC~2026-07-09~50",
   "origem": "tec",
   "data": "2026-07-09",
   "mat": "DAD",
   "topicId": "50",
   "assuntoLivre": "",
   "minutos": 68,
   "qResolvidas": 12,
   "qAcertadas": 9,
   "obs": "reconstruída do TEC (5 assuntos)"
  },
  {
   "uid": "TEC~2026-07-09~64",
   "origem": "tec",
   "data": "2026-07-09",
   "mat": "AUD",
   "topicId": "64",
   "assuntoLivre": "",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-09~67",
   "origem": "tec",
   "data": "2026-07-09",
   "mat": "AUD",
   "topicId": "67",
   "assuntoLivre": "",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-09~68",
   "origem": "tec",
   "data": "2026-07-09",
   "mat": "AUD",
   "topicId": "68",
   "assuntoLivre": "",
   "minutos": 11,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-09~74",
   "origem": "tec",
   "data": "2026-07-09",
   "mat": "AUD",
   "topicId": "74",
   "assuntoLivre": "",
   "minutos": 3,
   "qResolvidas": 2,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-09~78",
   "origem": "tec",
   "data": "2026-07-09",
   "mat": "AUD",
   "topicId": "78",
   "assuntoLivre": "",
   "minutos": 14,
   "qResolvidas": 1,
   "qAcertadas": 0,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-10~sem-assunto-dfc620",
   "origem": "tec",
   "data": "2026-07-10",
   "mat": "DFin",
   "topicId": null,
   "assuntoLivre": "AFO, Direito Financeiro e Contabilidade Pública — geral",
   "minutos": 7,
   "qResolvidas": 7,
   "qAcertadas": 7,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-10~sem-assunto-660b27",
   "origem": "tec",
   "data": "2026-07-10",
   "mat": "AUD",
   "topicId": null,
   "assuntoLivre": "Auditoria Governamental e Controle — geral",
   "minutos": 3,
   "qResolvidas": 2,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-10~sem-assunto-e4a453",
   "origem": "tec",
   "data": "2026-07-10",
   "mat": "DAD",
   "topicId": null,
   "assuntoLivre": "Direito Administrativo (Doutrina e Leis Federais) — geral",
   "minutos": 16,
   "qResolvidas": 7,
   "qAcertadas": 6,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-10~sem-assunto-ac28ba",
   "origem": "tec",
   "data": "2026-07-10",
   "mat": "Estat",
   "topicId": null,
   "assuntoLivre": "Estatística — geral",
   "minutos": 3,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-10~sem-assunto-3c157b",
   "origem": "tec",
   "data": "2026-07-10",
   "mat": "PORT",
   "topicId": null,
   "assuntoLivre": "Língua Portuguesa (Português) — geral",
   "minutos": 11,
   "qResolvidas": 9,
   "qAcertadas": 7,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-10~sem-assunto-036ef6",
   "origem": "tec",
   "data": "2026-07-10",
   "mat": "TI",
   "topicId": null,
   "assuntoLivre": "TI - Ciência de Dados e Inteligência Artificial — geral",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-10~104",
   "origem": "tec",
   "data": "2026-07-10",
   "mat": "DCON",
   "topicId": "104",
   "assuntoLivre": "",
   "minutos": 11,
   "qResolvidas": 11,
   "qAcertadas": 11,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-10~106",
   "origem": "tec",
   "data": "2026-07-10",
   "mat": "DCON",
   "topicId": "106",
   "assuntoLivre": "",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-10~113",
   "origem": "tec",
   "data": "2026-07-10",
   "mat": "TI",
   "topicId": "113",
   "assuntoLivre": "",
   "minutos": 16,
   "qResolvidas": 11,
   "qAcertadas": 6,
   "obs": "reconstruída do TEC (5 assuntos)"
  },
  {
   "uid": "TEC~2026-07-10~25",
   "origem": "tec",
   "data": "2026-07-10",
   "mat": "CG",
   "topicId": "25",
   "assuntoLivre": "",
   "minutos": 2,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-10~4",
   "origem": "tec",
   "data": "2026-07-10",
   "mat": "DFin",
   "topicId": "4",
   "assuntoLivre": "",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-10~41",
   "origem": "tec",
   "data": "2026-07-10",
   "mat": "CG",
   "topicId": "41",
   "assuntoLivre": "",
   "minutos": 3,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-10~68",
   "origem": "tec",
   "data": "2026-07-10",
   "mat": "AUD",
   "topicId": "68",
   "assuntoLivre": "",
   "minutos": 2,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-10~84",
   "origem": "tec",
   "data": "2026-07-10",
   "mat": "CASP",
   "topicId": "84",
   "assuntoLivre": "",
   "minutos": 5,
   "qResolvidas": 5,
   "qAcertadas": 4,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-10~85",
   "origem": "tec",
   "data": "2026-07-10",
   "mat": "CASP",
   "topicId": "85",
   "assuntoLivre": "",
   "minutos": 28,
   "qResolvidas": 28,
   "qAcertadas": 24,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-10~89",
   "origem": "tec",
   "data": "2026-07-10",
   "mat": "CASP",
   "topicId": "89",
   "assuntoLivre": "",
   "minutos": 12,
   "qResolvidas": 17,
   "qAcertadas": 15,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-13~10",
   "origem": "tec",
   "data": "2026-07-13",
   "mat": "DFin",
   "topicId": "10",
   "assuntoLivre": "",
   "minutos": 5,
   "qResolvidas": 4,
   "qAcertadas": 4,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-13~11",
   "origem": "tec",
   "data": "2026-07-13",
   "mat": "DFin",
   "topicId": "11",
   "assuntoLivre": "",
   "minutos": 13,
   "qResolvidas": 2,
   "qAcertadas": 2,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-13~18",
   "origem": "tec",
   "data": "2026-07-13",
   "mat": "DFin",
   "topicId": "18",
   "assuntoLivre": "",
   "minutos": 4,
   "qResolvidas": 3,
   "qAcertadas": 3,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-13~28",
   "origem": "tec",
   "data": "2026-07-13",
   "mat": "CG",
   "topicId": "28",
   "assuntoLivre": "",
   "minutos": 31,
   "qResolvidas": 21,
   "qAcertadas": 14,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-13~3",
   "origem": "tec",
   "data": "2026-07-13",
   "mat": "DFin",
   "topicId": "3",
   "assuntoLivre": "",
   "minutos": 6,
   "qResolvidas": 5,
   "qAcertadas": 3,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-13~65",
   "origem": "tec",
   "data": "2026-07-13",
   "mat": "AUD",
   "topicId": "65",
   "assuntoLivre": "",
   "minutos": 3,
   "qResolvidas": 4,
   "qAcertadas": 4,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-13~8",
   "origem": "tec",
   "data": "2026-07-13",
   "mat": "DFin",
   "topicId": "8",
   "assuntoLivre": "",
   "minutos": 5,
   "qResolvidas": 5,
   "qAcertadas": 3,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-13~84",
   "origem": "tec",
   "data": "2026-07-13",
   "mat": "CASP",
   "topicId": "84",
   "assuntoLivre": "",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-13~9",
   "origem": "tec",
   "data": "2026-07-13",
   "mat": "DFin",
   "topicId": "9",
   "assuntoLivre": "",
   "minutos": 13,
   "qResolvidas": 14,
   "qAcertadas": 8,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-14~outras-questoes-e-topicos-mesclados-de-auditoria-governament-9f3651",
   "origem": "tec",
   "data": "2026-07-14",
   "mat": "AUD",
   "topicId": null,
   "assuntoLivre": "Outras Questões e Tópicos Mesclados de Auditoria Governamental",
   "minutos": 6,
   "qResolvidas": 5,
   "qAcertadas": 3,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-14~sem-assunto-177bb3",
   "origem": "tec",
   "data": "2026-07-14",
   "mat": "DFin",
   "topicId": null,
   "assuntoLivre": "(sem assunto no TEC)",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 0,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-14~sem-assunto-660b27",
   "origem": "tec",
   "data": "2026-07-14",
   "mat": "AUD",
   "topicId": null,
   "assuntoLivre": "Auditoria Governamental e Controle — geral",
   "minutos": 4,
   "qResolvidas": 2,
   "qAcertadas": 2,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-14~105",
   "origem": "tec",
   "data": "2026-07-14",
   "mat": "DCON",
   "topicId": "105",
   "assuntoLivre": "",
   "minutos": 28,
   "qResolvidas": 12,
   "qAcertadas": 10,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-14~134",
   "origem": "tec",
   "data": "2026-07-14",
   "mat": "DCON",
   "topicId": "134",
   "assuntoLivre": "",
   "minutos": 22,
   "qResolvidas": 19,
   "qAcertadas": 17,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-14~29",
   "origem": "tec",
   "data": "2026-07-14",
   "mat": "CG",
   "topicId": "29",
   "assuntoLivre": "",
   "minutos": 19,
   "qResolvidas": 17,
   "qAcertadas": 13,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-14~51",
   "origem": "tec",
   "data": "2026-07-14",
   "mat": "DAD",
   "topicId": "51",
   "assuntoLivre": "",
   "minutos": 13,
   "qResolvidas": 9,
   "qAcertadas": 7,
   "obs": "reconstruída do TEC (3 assuntos)"
  },
  {
   "uid": "TEC~2026-07-14~55",
   "origem": "tec",
   "data": "2026-07-14",
   "mat": "DAD",
   "topicId": "55",
   "assuntoLivre": "",
   "minutos": 9,
   "qResolvidas": 8,
   "qAcertadas": 6,
   "obs": "reconstruída do TEC (4 assuntos)"
  },
  {
   "uid": "TEC~2026-07-14~58",
   "origem": "tec",
   "data": "2026-07-14",
   "mat": "DAD",
   "topicId": "58",
   "assuntoLivre": "",
   "minutos": 12,
   "qResolvidas": 10,
   "qAcertadas": 8,
   "obs": "reconstruída do TEC (4 assuntos)"
  },
  {
   "uid": "TEC~2026-07-14~63",
   "origem": "tec",
   "data": "2026-07-14",
   "mat": "DAD",
   "topicId": "63",
   "assuntoLivre": "",
   "minutos": 4,
   "qResolvidas": 4,
   "qAcertadas": 3,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-14~64",
   "origem": "tec",
   "data": "2026-07-14",
   "mat": "AUD",
   "topicId": "64",
   "assuntoLivre": "",
   "minutos": 2,
   "qResolvidas": 2,
   "qAcertadas": 2,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-14~65",
   "origem": "tec",
   "data": "2026-07-14",
   "mat": "AUD",
   "topicId": "65",
   "assuntoLivre": "",
   "minutos": 2,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-14~66",
   "origem": "tec",
   "data": "2026-07-14",
   "mat": "AUD",
   "topicId": "66",
   "assuntoLivre": "",
   "minutos": 2,
   "qResolvidas": 2,
   "qAcertadas": 2,
   "obs": "reconstruída do TEC (2 assuntos)"
  },
  {
   "uid": "TEC~2026-07-14~69",
   "origem": "tec",
   "data": "2026-07-14",
   "mat": "AUD",
   "topicId": "69",
   "assuntoLivre": "",
   "minutos": 1,
   "qResolvidas": 3,
   "qAcertadas": 3,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-14~72",
   "origem": "tec",
   "data": "2026-07-14",
   "mat": "AUD",
   "topicId": "72",
   "assuntoLivre": "",
   "minutos": 4,
   "qResolvidas": 2,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-14~78",
   "origem": "tec",
   "data": "2026-07-14",
   "mat": "AUD",
   "topicId": "78",
   "assuntoLivre": "",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 0,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-14~87",
   "origem": "tec",
   "data": "2026-07-14",
   "mat": "CASP",
   "topicId": "87",
   "assuntoLivre": "",
   "minutos": 5,
   "qResolvidas": 3,
   "qAcertadas": 3,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-14~88",
   "origem": "tec",
   "data": "2026-07-14",
   "mat": "CASP",
   "topicId": "88",
   "assuntoLivre": "",
   "minutos": 5,
   "qResolvidas": 6,
   "qAcertadas": 3,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-14~92",
   "origem": "tec",
   "data": "2026-07-14",
   "mat": "CASP",
   "topicId": "92",
   "assuntoLivre": "",
   "minutos": 37,
   "qResolvidas": 36,
   "qAcertadas": 30,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-15~115",
   "origem": "tec",
   "data": "2026-07-15",
   "mat": "TI",
   "topicId": "115",
   "assuntoLivre": "",
   "minutos": 60,
   "qResolvidas": 34,
   "qAcertadas": 28,
   "obs": "reconstruída do TEC (8 assuntos)"
  },
  {
   "uid": "TEC~2026-07-15~120",
   "origem": "tec",
   "data": "2026-07-15",
   "mat": "Estat",
   "topicId": "120",
   "assuntoLivre": "",
   "minutos": 11,
   "qResolvidas": 8,
   "qAcertadas": 5,
   "obs": "reconstruída do TEC (2 assuntos)"
  },
  {
   "uid": "TEC~2026-07-15~13",
   "origem": "tec",
   "data": "2026-07-15",
   "mat": "DFin",
   "topicId": "13",
   "assuntoLivre": "",
   "minutos": 8,
   "qResolvidas": 2,
   "qAcertadas": 2,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-15~14",
   "origem": "tec",
   "data": "2026-07-15",
   "mat": "DFin",
   "topicId": "14",
   "assuntoLivre": "",
   "minutos": 17,
   "qResolvidas": 10,
   "qAcertadas": 6,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-15~15",
   "origem": "tec",
   "data": "2026-07-15",
   "mat": "DFin",
   "topicId": "15",
   "assuntoLivre": "",
   "minutos": 21,
   "qResolvidas": 10,
   "qAcertadas": 8,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-15~18",
   "origem": "tec",
   "data": "2026-07-15",
   "mat": "DFin",
   "topicId": "18",
   "assuntoLivre": "",
   "minutos": 1,
   "qResolvidas": 2,
   "qAcertadas": 2,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-15~7",
   "origem": "tec",
   "data": "2026-07-15",
   "mat": "DFin",
   "topicId": "7",
   "assuntoLivre": "",
   "minutos": 11,
   "qResolvidas": 11,
   "qAcertadas": 7,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-16~estados-federados-organizacao-competencias-bens-arts-25-a-28-0452bc",
   "origem": "tec",
   "data": "2026-07-16",
   "mat": "DCON",
   "topicId": null,
   "assuntoLivre": "Estados Federados - Organização, Competências, Bens (arts. 25 a 28 da CF/1988)",
   "minutos": 3,
   "qResolvidas": 3,
   "qAcertadas": 3,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-16~questoes-envolvendo-diversos-assuntos-629606",
   "origem": "tec",
   "data": "2026-07-16",
   "mat": "CIVIL",
   "topicId": null,
   "assuntoLivre": "Questões Envolvendo Diversos Assuntos",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-16~sem-assunto-177bb3",
   "origem": "tec",
   "data": "2026-07-16",
   "mat": "DFin",
   "topicId": null,
   "assuntoLivre": "(sem assunto no TEC)",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 0,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-16~sem-assunto-660b27",
   "origem": "tec",
   "data": "2026-07-16",
   "mat": "AUD",
   "topicId": null,
   "assuntoLivre": "Auditoria Governamental e Controle — geral",
   "minutos": 3,
   "qResolvidas": 1,
   "qAcertadas": 0,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-16~117",
   "origem": "tec",
   "data": "2026-07-16",
   "mat": "TI",
   "topicId": "117",
   "assuntoLivre": "",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-16~135",
   "origem": "tec",
   "data": "2026-07-16",
   "mat": "DCON",
   "topicId": "135",
   "assuntoLivre": "",
   "minutos": 19,
   "qResolvidas": 13,
   "qAcertadas": 9,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-16~56",
   "origem": "tec",
   "data": "2026-07-16",
   "mat": "DAD",
   "topicId": "56",
   "assuntoLivre": "",
   "minutos": 24,
   "qResolvidas": 22,
   "qAcertadas": 14,
   "obs": "reconstruída do TEC (5 assuntos)"
  },
  {
   "uid": "TEC~2026-07-16~76",
   "origem": "tec",
   "data": "2026-07-16",
   "mat": "AUD",
   "topicId": "76",
   "assuntoLivre": "",
   "minutos": 22,
   "qResolvidas": 27,
   "qAcertadas": 21,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-17~sem-assunto-177bb3",
   "origem": "tec",
   "data": "2026-07-17",
   "mat": "DFin",
   "topicId": null,
   "assuntoLivre": "(sem assunto no TEC)",
   "minutos": 1,
   "qResolvidas": 2,
   "qAcertadas": 0,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-17~115",
   "origem": "tec",
   "data": "2026-07-17",
   "mat": "TI",
   "topicId": "115",
   "assuntoLivre": "",
   "minutos": 12,
   "qResolvidas": 19,
   "qAcertadas": 14,
   "obs": "reconstruída do TEC (7 assuntos)"
  },
  {
   "uid": "TEC~2026-07-17~12",
   "origem": "tec",
   "data": "2026-07-17",
   "mat": "DFin",
   "topicId": "12",
   "assuntoLivre": "",
   "minutos": 7,
   "qResolvidas": 5,
   "qAcertadas": 5,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-17~135",
   "origem": "tec",
   "data": "2026-07-17",
   "mat": "DCON",
   "topicId": "135",
   "assuntoLivre": "",
   "minutos": 2,
   "qResolvidas": 2,
   "qAcertadas": 2,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-17~14",
   "origem": "tec",
   "data": "2026-07-17",
   "mat": "DFin",
   "topicId": "14",
   "assuntoLivre": "",
   "minutos": 2,
   "qResolvidas": 2,
   "qAcertadas": 2,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-17~16",
   "origem": "tec",
   "data": "2026-07-17",
   "mat": "DFin",
   "topicId": "16",
   "assuntoLivre": "",
   "minutos": 35,
   "qResolvidas": 23,
   "qAcertadas": 17,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-17~28",
   "origem": "tec",
   "data": "2026-07-17",
   "mat": "CG",
   "topicId": "28",
   "assuntoLivre": "",
   "minutos": 5,
   "qResolvidas": 4,
   "qAcertadas": 4,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-17~29",
   "origem": "tec",
   "data": "2026-07-17",
   "mat": "CG",
   "topicId": "29",
   "assuntoLivre": "",
   "minutos": 1,
   "qResolvidas": 2,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-17~3",
   "origem": "tec",
   "data": "2026-07-17",
   "mat": "DFin",
   "topicId": "3",
   "assuntoLivre": "",
   "minutos": 2,
   "qResolvidas": 2,
   "qAcertadas": 2,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-17~56",
   "origem": "tec",
   "data": "2026-07-17",
   "mat": "DAD",
   "topicId": "56",
   "assuntoLivre": "",
   "minutos": 3,
   "qResolvidas": 4,
   "qAcertadas": 3,
   "obs": "reconstruída do TEC (2 assuntos)"
  },
  {
   "uid": "TEC~2026-07-17~7",
   "origem": "tec",
   "data": "2026-07-17",
   "mat": "DFin",
   "topicId": "7",
   "assuntoLivre": "",
   "minutos": 1,
   "qResolvidas": 2,
   "qAcertadas": 2,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-17~76",
   "origem": "tec",
   "data": "2026-07-17",
   "mat": "AUD",
   "topicId": "76",
   "assuntoLivre": "",
   "minutos": 1,
   "qResolvidas": 2,
   "qAcertadas": 2,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-17~85",
   "origem": "tec",
   "data": "2026-07-17",
   "mat": "CASP",
   "topicId": "85",
   "assuntoLivre": "",
   "minutos": 5,
   "qResolvidas": 4,
   "qAcertadas": 4,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-17~9",
   "origem": "tec",
   "data": "2026-07-17",
   "mat": "DFin",
   "topicId": "9",
   "assuntoLivre": "",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 0,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-17~90",
   "origem": "tec",
   "data": "2026-07-17",
   "mat": "CASP",
   "topicId": "90",
   "assuntoLivre": "",
   "minutos": 15,
   "qResolvidas": 17,
   "qAcertadas": 14,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-17~91",
   "origem": "tec",
   "data": "2026-07-17",
   "mat": "CASP",
   "topicId": "91",
   "assuntoLivre": "",
   "minutos": 11,
   "qResolvidas": 6,
   "qAcertadas": 5,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-17~92",
   "origem": "tec",
   "data": "2026-07-17",
   "mat": "CASP",
   "topicId": "92",
   "assuntoLivre": "",
   "minutos": 2,
   "qResolvidas": 4,
   "qAcertadas": 3,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-20~sem-assunto-177bb3",
   "origem": "tec",
   "data": "2026-07-20",
   "mat": "DFin",
   "topicId": null,
   "assuntoLivre": "(sem assunto no TEC)",
   "minutos": 1,
   "qResolvidas": 2,
   "qAcertadas": 0,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-20~19",
   "origem": "tec",
   "data": "2026-07-20",
   "mat": "DFin",
   "topicId": "19",
   "assuntoLivre": "",
   "minutos": 7,
   "qResolvidas": 5,
   "qAcertadas": 5,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-20~20",
   "origem": "tec",
   "data": "2026-07-20",
   "mat": "DFin",
   "topicId": "20",
   "assuntoLivre": "",
   "minutos": 5,
   "qResolvidas": 6,
   "qAcertadas": 3,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-20~21",
   "origem": "tec",
   "data": "2026-07-20",
   "mat": "DFin",
   "topicId": "21",
   "assuntoLivre": "",
   "minutos": 12,
   "qResolvidas": 12,
   "qAcertadas": 8,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-20~22",
   "origem": "tec",
   "data": "2026-07-20",
   "mat": "DFin",
   "topicId": "22",
   "assuntoLivre": "",
   "minutos": 15,
   "qResolvidas": 7,
   "qAcertadas": 5,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-20~3",
   "origem": "tec",
   "data": "2026-07-20",
   "mat": "DFin",
   "topicId": "3",
   "assuntoLivre": "",
   "minutos": 3,
   "qResolvidas": 3,
   "qAcertadas": 3,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-20~30",
   "origem": "tec",
   "data": "2026-07-20",
   "mat": "CG",
   "topicId": "30",
   "assuntoLivre": "",
   "minutos": 23,
   "qResolvidas": 14,
   "qAcertadas": 11,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-20~52",
   "origem": "tec",
   "data": "2026-07-20",
   "mat": "DAD",
   "topicId": "52",
   "assuntoLivre": "",
   "minutos": 15,
   "qResolvidas": 9,
   "qAcertadas": 8,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-20~53",
   "origem": "tec",
   "data": "2026-07-20",
   "mat": "DAD",
   "topicId": "53",
   "assuntoLivre": "",
   "minutos": 14,
   "qResolvidas": 10,
   "qAcertadas": 7,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-20~59",
   "origem": "tec",
   "data": "2026-07-20",
   "mat": "DAD",
   "topicId": "59",
   "assuntoLivre": "",
   "minutos": 18,
   "qResolvidas": 14,
   "qAcertadas": 10,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-20~9",
   "origem": "tec",
   "data": "2026-07-20",
   "mat": "DFin",
   "topicId": "9",
   "assuntoLivre": "",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-20~90",
   "origem": "tec",
   "data": "2026-07-20",
   "mat": "CASP",
   "topicId": "90",
   "assuntoLivre": "",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-20~92",
   "origem": "tec",
   "data": "2026-07-20",
   "mat": "CASP",
   "topicId": "92",
   "assuntoLivre": "",
   "minutos": 2,
   "qResolvidas": 3,
   "qAcertadas": 3,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-21~sem-assunto-177bb3",
   "origem": "tec",
   "data": "2026-07-21",
   "mat": "DFin",
   "topicId": null,
   "assuntoLivre": "(sem assunto no TEC)",
   "minutos": 1,
   "qResolvidas": 2,
   "qAcertadas": 0,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-21~sem-assunto-3c157b",
   "origem": "tec",
   "data": "2026-07-21",
   "mat": "PORT",
   "topicId": null,
   "assuntoLivre": "Língua Portuguesa (Português) — geral",
   "minutos": 14,
   "qResolvidas": 10,
   "qAcertadas": 9,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-21~109",
   "origem": "tec",
   "data": "2026-07-21",
   "mat": "DCON",
   "topicId": "109",
   "assuntoLivre": "",
   "minutos": 47,
   "qResolvidas": 5,
   "qAcertadas": 4,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-21~137",
   "origem": "tec",
   "data": "2026-07-21",
   "mat": "DCON",
   "topicId": "137",
   "assuntoLivre": "",
   "minutos": 10,
   "qResolvidas": 9,
   "qAcertadas": 5,
   "obs": "reconstruída do TEC (2 assuntos)"
  },
  {
   "uid": "TEC~2026-07-21~28",
   "origem": "tec",
   "data": "2026-07-21",
   "mat": "CG",
   "topicId": "28",
   "assuntoLivre": "",
   "minutos": 2,
   "qResolvidas": 3,
   "qAcertadas": 3,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-21~29",
   "origem": "tec",
   "data": "2026-07-21",
   "mat": "CG",
   "topicId": "29",
   "assuntoLivre": "",
   "minutos": 4,
   "qResolvidas": 6,
   "qAcertadas": 5,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-21~31",
   "origem": "tec",
   "data": "2026-07-21",
   "mat": "CG",
   "topicId": "31",
   "assuntoLivre": "",
   "minutos": 51,
   "qResolvidas": 15,
   "qAcertadas": 6,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-21~56",
   "origem": "tec",
   "data": "2026-07-21",
   "mat": "DAD",
   "topicId": "56",
   "assuntoLivre": "",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-21~7",
   "origem": "tec",
   "data": "2026-07-21",
   "mat": "DFin",
   "topicId": "7",
   "assuntoLivre": "",
   "minutos": 1,
   "qResolvidas": 2,
   "qAcertadas": 2,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-21~75",
   "origem": "tec",
   "data": "2026-07-21",
   "mat": "AUD",
   "topicId": "75",
   "assuntoLivre": "",
   "minutos": 9,
   "qResolvidas": 12,
   "qAcertadas": 11,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-21~77",
   "origem": "tec",
   "data": "2026-07-21",
   "mat": "AUD",
   "topicId": "77",
   "assuntoLivre": "",
   "minutos": 36,
   "qResolvidas": 18,
   "qAcertadas": 15,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-21~88",
   "origem": "tec",
   "data": "2026-07-21",
   "mat": "CASP",
   "topicId": "88",
   "assuntoLivre": "",
   "minutos": 4,
   "qResolvidas": 8,
   "qAcertadas": 8,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-21~9",
   "origem": "tec",
   "data": "2026-07-21",
   "mat": "DFin",
   "topicId": "9",
   "assuntoLivre": "",
   "minutos": 3,
   "qResolvidas": 5,
   "qAcertadas": 3,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-21~92",
   "origem": "tec",
   "data": "2026-07-21",
   "mat": "CASP",
   "topicId": "92",
   "assuntoLivre": "",
   "minutos": 2,
   "qResolvidas": 2,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-21~93",
   "origem": "tec",
   "data": "2026-07-21",
   "mat": "CASP",
   "topicId": "93",
   "assuntoLivre": "",
   "minutos": 13,
   "qResolvidas": 14,
   "qAcertadas": 13,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-21~96",
   "origem": "tec",
   "data": "2026-07-21",
   "mat": "CASP",
   "topicId": "96",
   "assuntoLivre": "",
   "minutos": 19,
   "qResolvidas": 21,
   "qAcertadas": 17,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-22~116",
   "origem": "tec",
   "data": "2026-07-22",
   "mat": "TI",
   "topicId": "116",
   "assuntoLivre": "",
   "minutos": 24,
   "qResolvidas": 62,
   "qAcertadas": 52,
   "obs": "reconstruída do TEC (3 assuntos)"
  },
  {
   "uid": "TEC~2026-07-22~121",
   "origem": "tec",
   "data": "2026-07-22",
   "mat": "Estat",
   "topicId": "121",
   "assuntoLivre": "",
   "minutos": 27,
   "qResolvidas": 9,
   "qAcertadas": 8,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-22~17",
   "origem": "tec",
   "data": "2026-07-22",
   "mat": "DFin",
   "topicId": "17",
   "assuntoLivre": "",
   "minutos": 32,
   "qResolvidas": 25,
   "qAcertadas": 21,
   "obs": "reconstruída do TEC (2 assuntos)"
  },
  {
   "uid": "TEC~2026-07-22~24",
   "origem": "tec",
   "data": "2026-07-22",
   "mat": "DFin",
   "topicId": "24",
   "assuntoLivre": "",
   "minutos": 7,
   "qResolvidas": 9,
   "qAcertadas": 8,
   "obs": "reconstruída do TEC (2 assuntos)"
  },
  {
   "uid": "TEC~2026-07-22~32",
   "origem": "tec",
   "data": "2026-07-22",
   "mat": "CG",
   "topicId": "32",
   "assuntoLivre": "",
   "minutos": 39,
   "qResolvidas": 13,
   "qAcertadas": 10,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-22~76",
   "origem": "tec",
   "data": "2026-07-22",
   "mat": "AUD",
   "topicId": "76",
   "assuntoLivre": "",
   "minutos": 6,
   "qResolvidas": 6,
   "qAcertadas": 6,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-23~cpc-06-arrendamento-mercantil-financeiro-e-operacional-503b44",
   "origem": "tec",
   "data": "2026-07-23",
   "mat": "CG",
   "topicId": null,
   "assuntoLivre": "CPC 06: Arrendamento Mercantil (Financeiro e Operacional)",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-23~cpc-46-mensuracao-a-valor-justo-lei-6-404-art-183-1-e4bdf6",
   "origem": "tec",
   "data": "2026-07-23",
   "mat": "CG",
   "topicId": null,
   "assuntoLivre": "CPC 46: Mensuração a Valor Justo (Lei 6.404, art. 183, §1º)",
   "minutos": 2,
   "qResolvidas": 1,
   "qAcertadas": 0,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-23~dos-principios-gerais-sistema-tributario-nacional-arts-145-a-d74c3d",
   "origem": "tec",
   "data": "2026-07-23",
   "mat": "DCON",
   "topicId": null,
   "assuntoLivre": "Dos Princípios Gerais (Sistema Tributário Nacional, arts. 145 a 149-B da CF/1988)",
   "minutos": 2,
   "qResolvidas": 2,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-23~natureza-e-elementos-dos-contratos-de-seguro-previdencia-sau-ed43f2",
   "origem": "tec",
   "data": "2026-07-23",
   "mat": "DPREV",
   "topicId": null,
   "assuntoLivre": "Natureza e elementos dos contratos de seguro, previdência saúde e capitalização",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-23~nota-tecnica-atuarial-7090d1",
   "origem": "tec",
   "data": "2026-07-23",
   "mat": "DPREV",
   "topicId": null,
   "assuntoLivre": "Nota Técnica Atuarial",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-23~outras-questoes-de-ciencias-atuariais-3ed77b",
   "origem": "tec",
   "data": "2026-07-23",
   "mat": "DPREV",
   "topicId": null,
   "assuntoLivre": "Outras questões de Ciências Atuariais",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-23~propriedades-para-investimento-cpc-28-adfa5a",
   "origem": "tec",
   "data": "2026-07-23",
   "mat": "CG",
   "topicId": null,
   "assuntoLivre": "Propriedades para Investimento (CPC 28)",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-23~provisoes-passivos-e-ativos-contingentes-cpc-25-lei-6-404-118bf5",
   "origem": "tec",
   "data": "2026-07-23",
   "mat": "CG",
   "topicId": null,
   "assuntoLivre": "Provisões, Passivos e Ativos Contingentes (CPC 25, Lei 6.404)",
   "minutos": 4,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-23~regimes-e-metodos-financeiros-e19a49",
   "origem": "tec",
   "data": "2026-07-23",
   "mat": "DPREV",
   "topicId": null,
   "assuntoLivre": "Regimes e Métodos Financeiros",
   "minutos": 5,
   "qResolvidas": 3,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-23~riscos-e-incertezas-72f7d8",
   "origem": "tec",
   "data": "2026-07-23",
   "mat": "DPREV",
   "topicId": null,
   "assuntoLivre": "Riscos e incertezas",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-23~sem-assunto-177bb3",
   "origem": "tec",
   "data": "2026-07-23",
   "mat": "DFin",
   "topicId": null,
   "assuntoLivre": "(sem assunto no TEC)",
   "minutos": 1,
   "qResolvidas": 9,
   "qAcertadas": 0,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-23~sem-assunto-dfc620",
   "origem": "tec",
   "data": "2026-07-23",
   "mat": "DFin",
   "topicId": null,
   "assuntoLivre": "AFO, Direito Financeiro e Contabilidade Pública — geral",
   "minutos": 8,
   "qResolvidas": 7,
   "qAcertadas": 5,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-23~sem-assunto-2c6431",
   "origem": "tec",
   "data": "2026-07-23",
   "mat": "CG",
   "topicId": null,
   "assuntoLivre": "Contabilidade Geral — geral",
   "minutos": 8,
   "qResolvidas": 4,
   "qAcertadas": 2,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-23~sem-assunto-7dd753",
   "origem": "tec",
   "data": "2026-07-23",
   "mat": "TRIB",
   "topicId": null,
   "assuntoLivre": "Direito Tributário — geral",
   "minutos": 2,
   "qResolvidas": 1,
   "qAcertadas": 0,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-23~sem-assunto-3c157b",
   "origem": "tec",
   "data": "2026-07-23",
   "mat": "PORT",
   "topicId": null,
   "assuntoLivre": "Língua Portuguesa (Português) — geral",
   "minutos": 1,
   "qResolvidas": 2,
   "qAcertadas": 2,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-23~118",
   "origem": "tec",
   "data": "2026-07-23",
   "mat": "Estat",
   "topicId": "118",
   "assuntoLivre": "",
   "minutos": 8,
   "qResolvidas": 2,
   "qAcertadas": 2,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-23~119",
   "origem": "tec",
   "data": "2026-07-23",
   "mat": "Estat",
   "topicId": "119",
   "assuntoLivre": "",
   "minutos": 5,
   "qResolvidas": 2,
   "qAcertadas": 2,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-23~120",
   "origem": "tec",
   "data": "2026-07-23",
   "mat": "Estat",
   "topicId": "120",
   "assuntoLivre": "",
   "minutos": 2,
   "qResolvidas": 2,
   "qAcertadas": 2,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-23~136",
   "origem": "tec",
   "data": "2026-07-23",
   "mat": "DCON",
   "topicId": "136",
   "assuntoLivre": "",
   "minutos": 58,
   "qResolvidas": 5,
   "qAcertadas": 3,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-23~14",
   "origem": "tec",
   "data": "2026-07-23",
   "mat": "DFin",
   "topicId": "14",
   "assuntoLivre": "",
   "minutos": 4,
   "qResolvidas": 4,
   "qAcertadas": 3,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-23~15",
   "origem": "tec",
   "data": "2026-07-23",
   "mat": "DFin",
   "topicId": "15",
   "assuntoLivre": "",
   "minutos": 6,
   "qResolvidas": 5,
   "qAcertadas": 4,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-23~20",
   "origem": "tec",
   "data": "2026-07-23",
   "mat": "DFin",
   "topicId": "20",
   "assuntoLivre": "",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-23~29",
   "origem": "tec",
   "data": "2026-07-23",
   "mat": "CG",
   "topicId": "29",
   "assuntoLivre": "",
   "minutos": 2,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-23~32",
   "origem": "tec",
   "data": "2026-07-23",
   "mat": "CG",
   "topicId": "32",
   "assuntoLivre": "",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-23~37",
   "origem": "tec",
   "data": "2026-07-23",
   "mat": "CG",
   "topicId": "37",
   "assuntoLivre": "",
   "minutos": 2,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-23~38",
   "origem": "tec",
   "data": "2026-07-23",
   "mat": "CG",
   "topicId": "38",
   "assuntoLivre": "",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-23~39",
   "origem": "tec",
   "data": "2026-07-23",
   "mat": "CG",
   "topicId": "39",
   "assuntoLivre": "",
   "minutos": 2,
   "qResolvidas": 1,
   "qAcertadas": 0,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-23~45",
   "origem": "tec",
   "data": "2026-07-23",
   "mat": "CG",
   "topicId": "45",
   "assuntoLivre": "",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-23~54",
   "origem": "tec",
   "data": "2026-07-23",
   "mat": "DAD",
   "topicId": "54",
   "assuntoLivre": "",
   "minutos": 2,
   "qResolvidas": 2,
   "qAcertadas": 2,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-23~57",
   "origem": "tec",
   "data": "2026-07-23",
   "mat": "DAD",
   "topicId": "57",
   "assuntoLivre": "",
   "minutos": 27,
   "qResolvidas": 21,
   "qAcertadas": 17,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-23~7",
   "origem": "tec",
   "data": "2026-07-23",
   "mat": "DFin",
   "topicId": "7",
   "assuntoLivre": "",
   "minutos": 3,
   "qResolvidas": 6,
   "qAcertadas": 5,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-23~80",
   "origem": "tec",
   "data": "2026-07-23",
   "mat": "AUD",
   "topicId": "80",
   "assuntoLivre": "",
   "minutos": 31,
   "qResolvidas": 25,
   "qAcertadas": 18,
   "obs": "reconstruída do TEC (2 assuntos)"
  },
  {
   "uid": "TEC~2026-07-24~jurisprudencia-dos-tribunais-superiores-sobre-topicos-mescla-582a95",
   "origem": "tec",
   "data": "2026-07-24",
   "mat": "TRIB",
   "topicId": null,
   "assuntoLivre": "Jurisprudência dos Tribunais Superiores sobre Tópicos Mesclados e/ou Outros Assuntos Tributários",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-24~sem-assunto-dfc620",
   "origem": "tec",
   "data": "2026-07-24",
   "mat": "DFin",
   "topicId": null,
   "assuntoLivre": "AFO, Direito Financeiro e Contabilidade Pública — geral",
   "minutos": 5,
   "qResolvidas": 6,
   "qAcertadas": 6,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-24~sem-assunto-1ff7bb",
   "origem": "tec",
   "data": "2026-07-24",
   "mat": "AUD",
   "topicId": null,
   "assuntoLivre": "Auditoria Privada — geral",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-24~sem-assunto-2c6431",
   "origem": "tec",
   "data": "2026-07-24",
   "mat": "CG",
   "topicId": null,
   "assuntoLivre": "Contabilidade Geral — geral",
   "minutos": 3,
   "qResolvidas": 2,
   "qAcertadas": 2,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-24~1",
   "origem": "tec",
   "data": "2026-07-24",
   "mat": "DFin",
   "topicId": "1",
   "assuntoLivre": "",
   "minutos": 20,
   "qResolvidas": 21,
   "qAcertadas": 19,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-24~109",
   "origem": "tec",
   "data": "2026-07-24",
   "mat": "DCON",
   "topicId": "109",
   "assuntoLivre": "",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-24~113",
   "origem": "tec",
   "data": "2026-07-24",
   "mat": "TI",
   "topicId": "113",
   "assuntoLivre": "",
   "minutos": 19,
   "qResolvidas": 10,
   "qAcertadas": 5,
   "obs": "reconstruída do TEC (4 assuntos)"
  },
  {
   "uid": "TEC~2026-07-24~127",
   "origem": "tec",
   "data": "2026-07-24",
   "mat": "CASP",
   "topicId": "127",
   "assuntoLivre": "",
   "minutos": 10,
   "qResolvidas": 15,
   "qAcertadas": 14,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-24~136",
   "origem": "tec",
   "data": "2026-07-24",
   "mat": "DCON",
   "topicId": "136",
   "assuntoLivre": "",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-24~137",
   "origem": "tec",
   "data": "2026-07-24",
   "mat": "DCON",
   "topicId": "137",
   "assuntoLivre": "",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-24~15",
   "origem": "tec",
   "data": "2026-07-24",
   "mat": "DFin",
   "topicId": "15",
   "assuntoLivre": "",
   "minutos": 5,
   "qResolvidas": 3,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-24~16",
   "origem": "tec",
   "data": "2026-07-24",
   "mat": "DFin",
   "topicId": "16",
   "assuntoLivre": "",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-24~17",
   "origem": "tec",
   "data": "2026-07-24",
   "mat": "DFin",
   "topicId": "17",
   "assuntoLivre": "",
   "minutos": 5,
   "qResolvidas": 4,
   "qAcertadas": 4,
   "obs": "reconstruída do TEC (2 assuntos)"
  },
  {
   "uid": "TEC~2026-07-24~2",
   "origem": "tec",
   "data": "2026-07-24",
   "mat": "DFin",
   "topicId": "2",
   "assuntoLivre": "",
   "minutos": 15,
   "qResolvidas": 13,
   "qAcertadas": 11,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-24~21",
   "origem": "tec",
   "data": "2026-07-24",
   "mat": "DFin",
   "topicId": "21",
   "assuntoLivre": "",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-24~23",
   "origem": "tec",
   "data": "2026-07-24",
   "mat": "DFin",
   "topicId": "23",
   "assuntoLivre": "",
   "minutos": 21,
   "qResolvidas": 5,
   "qAcertadas": 4,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-24~3",
   "origem": "tec",
   "data": "2026-07-24",
   "mat": "DFin",
   "topicId": "3",
   "assuntoLivre": "",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-24~30",
   "origem": "tec",
   "data": "2026-07-24",
   "mat": "CG",
   "topicId": "30",
   "assuntoLivre": "",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-24~31",
   "origem": "tec",
   "data": "2026-07-24",
   "mat": "CG",
   "topicId": "31",
   "assuntoLivre": "",
   "minutos": 3,
   "qResolvidas": 3,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-24~32",
   "origem": "tec",
   "data": "2026-07-24",
   "mat": "CG",
   "topicId": "32",
   "assuntoLivre": "",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-24~53",
   "origem": "tec",
   "data": "2026-07-24",
   "mat": "DAD",
   "topicId": "53",
   "assuntoLivre": "",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 0,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-24~77",
   "origem": "tec",
   "data": "2026-07-24",
   "mat": "AUD",
   "topicId": "77",
   "assuntoLivre": "",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-24~95",
   "origem": "tec",
   "data": "2026-07-24",
   "mat": "CASP",
   "topicId": "95",
   "assuntoLivre": "",
   "minutos": 14,
   "qResolvidas": 18,
   "qAcertadas": 15,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-27~conceito-objeto-finalidade-tecnicas-contabeis-equacao-patrim-37be13",
   "origem": "tec",
   "data": "2026-07-27",
   "mat": "CG",
   "topicId": null,
   "assuntoLivre": "Conceito, Objeto, Finalidade, Técnicas Contábeis, Equação Patrimonial",
   "minutos": 6,
   "qResolvidas": 4,
   "qAcertadas": 3,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-27~sem-assunto-177bb3",
   "origem": "tec",
   "data": "2026-07-27",
   "mat": "DFin",
   "topicId": null,
   "assuntoLivre": "(sem assunto no TEC)",
   "minutos": 1,
   "qResolvidas": 2,
   "qAcertadas": 0,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-27~140",
   "origem": "tec",
   "data": "2026-07-27",
   "mat": "CIVIL",
   "topicId": "140",
   "assuntoLivre": "",
   "minutos": 28,
   "qResolvidas": 10,
   "qAcertadas": 5,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-27~141",
   "origem": "tec",
   "data": "2026-07-27",
   "mat": "CIVIL",
   "topicId": "141",
   "assuntoLivre": "",
   "minutos": 8,
   "qResolvidas": 5,
   "qAcertadas": 5,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-27~3",
   "origem": "tec",
   "data": "2026-07-27",
   "mat": "DFin",
   "topicId": "3",
   "assuntoLivre": "",
   "minutos": 33,
   "qResolvidas": 33,
   "qAcertadas": 25,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-27~33",
   "origem": "tec",
   "data": "2026-07-27",
   "mat": "CG",
   "topicId": "33",
   "assuntoLivre": "",
   "minutos": 25,
   "qResolvidas": 13,
   "qAcertadas": 9,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-27~35",
   "origem": "tec",
   "data": "2026-07-27",
   "mat": "CG",
   "topicId": "35",
   "assuntoLivre": "",
   "minutos": 9,
   "qResolvidas": 17,
   "qAcertadas": 14,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-27~4",
   "origem": "tec",
   "data": "2026-07-27",
   "mat": "DFin",
   "topicId": "4",
   "assuntoLivre": "",
   "minutos": 10,
   "qResolvidas": 10,
   "qAcertadas": 10,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-27~61",
   "origem": "tec",
   "data": "2026-07-27",
   "mat": "DAD",
   "topicId": "61",
   "assuntoLivre": "",
   "minutos": 19,
   "qResolvidas": 14,
   "qAcertadas": 13,
   "obs": "reconstruída do TEC (2 assuntos)"
  },
  {
   "uid": "TEC~2026-07-27~62",
   "origem": "tec",
   "data": "2026-07-27",
   "mat": "DAD",
   "topicId": "62",
   "assuntoLivre": "",
   "minutos": 15,
   "qResolvidas": 19,
   "qAcertadas": 16,
   "obs": "reconstruída do TEC (7 assuntos)"
  },
  {
   "uid": "TEC~2026-07-27~63",
   "origem": "tec",
   "data": "2026-07-27",
   "mat": "DAD",
   "topicId": "63",
   "assuntoLivre": "",
   "minutos": 7,
   "qResolvidas": 5,
   "qAcertadas": 3,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-28~sem-assunto-177bb3",
   "origem": "tec",
   "data": "2026-07-28",
   "mat": "DFin",
   "topicId": null,
   "assuntoLivre": "(sem assunto no TEC)",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 0,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-28~128",
   "origem": "tec",
   "data": "2026-07-28",
   "mat": "CASP",
   "topicId": "128",
   "assuntoLivre": "",
   "minutos": 13,
   "qResolvidas": 10,
   "qAcertadas": 9,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-28~129",
   "origem": "tec",
   "data": "2026-07-28",
   "mat": "CASP",
   "topicId": "129",
   "assuntoLivre": "",
   "minutos": 4,
   "qResolvidas": 8,
   "qAcertadas": 8,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-28~130",
   "origem": "tec",
   "data": "2026-07-28",
   "mat": "CASP",
   "topicId": "130",
   "assuntoLivre": "",
   "minutos": 11,
   "qResolvidas": 9,
   "qAcertadas": 8,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-28~147",
   "origem": "tec",
   "data": "2026-07-28",
   "mat": "PROC",
   "topicId": "147",
   "assuntoLivre": "",
   "minutos": 22,
   "qResolvidas": 17,
   "qAcertadas": 11,
   "obs": "reconstruída do TEC (2 assuntos)"
  },
  {
   "uid": "TEC~2026-07-28~19",
   "origem": "tec",
   "data": "2026-07-28",
   "mat": "DFin",
   "topicId": "19",
   "assuntoLivre": "",
   "minutos": 8,
   "qResolvidas": 3,
   "qAcertadas": 2,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-28~20",
   "origem": "tec",
   "data": "2026-07-28",
   "mat": "DFin",
   "topicId": "20",
   "assuntoLivre": "",
   "minutos": 2,
   "qResolvidas": 3,
   "qAcertadas": 3,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-28~21",
   "origem": "tec",
   "data": "2026-07-28",
   "mat": "DFin",
   "topicId": "21",
   "assuntoLivre": "",
   "minutos": 2,
   "qResolvidas": 3,
   "qAcertadas": 3,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-28~22",
   "origem": "tec",
   "data": "2026-07-28",
   "mat": "DFin",
   "topicId": "22",
   "assuntoLivre": "",
   "minutos": 1,
   "qResolvidas": 2,
   "qAcertadas": 2,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-28~33",
   "origem": "tec",
   "data": "2026-07-28",
   "mat": "CG",
   "topicId": "33",
   "assuntoLivre": "",
   "minutos": 26,
   "qResolvidas": 12,
   "qAcertadas": 8,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-28~34",
   "origem": "tec",
   "data": "2026-07-28",
   "mat": "CG",
   "topicId": "34",
   "assuntoLivre": "",
   "minutos": 9,
   "qResolvidas": 6,
   "qAcertadas": 4,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-28~64",
   "origem": "tec",
   "data": "2026-07-28",
   "mat": "AUD",
   "topicId": "64",
   "assuntoLivre": "",
   "minutos": 2,
   "qResolvidas": 2,
   "qAcertadas": 2,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-28~74",
   "origem": "tec",
   "data": "2026-07-28",
   "mat": "AUD",
   "topicId": "74",
   "assuntoLivre": "",
   "minutos": 25,
   "qResolvidas": 15,
   "qAcertadas": 14,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-28~78",
   "origem": "tec",
   "data": "2026-07-28",
   "mat": "AUD",
   "topicId": "78",
   "assuntoLivre": "",
   "minutos": 11,
   "qResolvidas": 7,
   "qAcertadas": 5,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-28~81",
   "origem": "tec",
   "data": "2026-07-28",
   "mat": "AUD",
   "topicId": "81",
   "assuntoLivre": "",
   "minutos": 4,
   "qResolvidas": 5,
   "qAcertadas": 3,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-28~82",
   "origem": "tec",
   "data": "2026-07-28",
   "mat": "AUD",
   "topicId": "82",
   "assuntoLivre": "",
   "minutos": 2,
   "qResolvidas": 2,
   "qAcertadas": 2,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-28~97",
   "origem": "tec",
   "data": "2026-07-28",
   "mat": "CASP",
   "topicId": "97",
   "assuntoLivre": "",
   "minutos": 6,
   "qResolvidas": 8,
   "qAcertadas": 7,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-29~jurisprudencia-dos-tribunais-superiores-sobre-controle-de-co-110b84",
   "origem": "tec",
   "data": "2026-07-29",
   "mat": "DCON",
   "topicId": null,
   "assuntoLivre": "Jurisprudência dos Tribunais Superiores sobre Controle de Constitucionalidade",
   "minutos": 2,
   "qResolvidas": 1,
   "qAcertadas": 0,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-29~sem-assunto-177bb3",
   "origem": "tec",
   "data": "2026-07-29",
   "mat": "DFin",
   "topicId": null,
   "assuntoLivre": "(sem assunto no TEC)",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 0,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-29~111",
   "origem": "tec",
   "data": "2026-07-29",
   "mat": "DCON",
   "topicId": "111",
   "assuntoLivre": "",
   "minutos": 41,
   "qResolvidas": 25,
   "qAcertadas": 22,
   "obs": "reconstruída do TEC (3 assuntos)"
  },
  {
   "uid": "TEC~2026-07-29~112",
   "origem": "tec",
   "data": "2026-07-29",
   "mat": "DCON",
   "topicId": "112",
   "assuntoLivre": "",
   "minutos": 10,
   "qResolvidas": 9,
   "qAcertadas": 6,
   "obs": "reconstruída do TEC (3 assuntos)"
  },
  {
   "uid": "TEC~2026-07-29~146",
   "origem": "tec",
   "data": "2026-07-29",
   "mat": "PROC",
   "topicId": "146",
   "assuntoLivre": "",
   "minutos": 7,
   "qResolvidas": 6,
   "qAcertadas": 3,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-29~148",
   "origem": "tec",
   "data": "2026-07-29",
   "mat": "PROC",
   "topicId": "148",
   "assuntoLivre": "",
   "minutos": 18,
   "qResolvidas": 17,
   "qAcertadas": 13,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-29~34",
   "origem": "tec",
   "data": "2026-07-29",
   "mat": "CG",
   "topicId": "34",
   "assuntoLivre": "",
   "minutos": 43,
   "qResolvidas": 14,
   "qAcertadas": 10,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-30~cpc-07-subvencao-e-assistencia-governamentais-a9ae16",
   "origem": "tec",
   "data": "2026-07-30",
   "mat": "CG",
   "topicId": null,
   "assuntoLivre": "CPC 07: Subvenção e Assistência Governamentais",
   "minutos": 1,
   "qResolvidas": 2,
   "qAcertadas": 2,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-30~cpc-15-combinacao-de-negocios-fusao-incorporacao-e-cisao-1a73c6",
   "origem": "tec",
   "data": "2026-07-30",
   "mat": "CG",
   "topicId": null,
   "assuntoLivre": "CPC 15: Combinação de Negócios, Fusão, Incorporação e Cisão",
   "minutos": 2,
   "qResolvidas": 3,
   "qAcertadas": 2,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-30~controle-de-constitucionalidade-pelos-tribunais-de-justica-d-c56f4c",
   "origem": "tec",
   "data": "2026-07-30",
   "mat": "DCON",
   "topicId": null,
   "assuntoLivre": "Controle de Constitucionalidade pelos Tribunais de Justiça dos Estados",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 0,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-30~calculo-de-probabilidades-usando-analise-combinatoria-d8085a",
   "origem": "tec",
   "data": "2026-07-30",
   "mat": "Estat",
   "topicId": null,
   "assuntoLivre": "Cálculo de Probabilidades Usando Análise Combinatória",
   "minutos": 29,
   "qResolvidas": 7,
   "qAcertadas": 6,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-30~da-responsabilidade-civil-arts-927-a-954-787b52",
   "origem": "tec",
   "data": "2026-07-30",
   "mat": "CIVIL",
   "topicId": null,
   "assuntoLivre": "Da Responsabilidade Civil (arts. 927 a 954)",
   "minutos": 20,
   "qResolvidas": 15,
   "qAcertadas": 11,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-30~da-saude-arts-196-a-200-da-cf-1988-0836b2",
   "origem": "tec",
   "data": "2026-07-30",
   "mat": "DCON",
   "topicId": null,
   "assuntoLivre": "Da Saúde (arts. 196 a 200 da CF/1988)",
   "minutos": 2,
   "qResolvidas": 3,
   "qAcertadas": 3,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-30~decreto-estadual-n-54-700-2023-regulamenta-o-sistema-de-regi-f1142b",
   "origem": "tec",
   "data": "2026-07-30",
   "mat": "DAD",
   "topicId": null,
   "assuntoLivre": "Decreto Estadual nº 54.700/2023 - Regulamenta o Sistema de Registro de Preços no Âmbito da Administração Pública Direta e Indireta (PE)",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 0,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-30~demonstracao-contabil-consolidada-cpc-36-lei-6-404-art-249-e-ba8d90",
   "origem": "tec",
   "data": "2026-07-30",
   "mat": "CG",
   "topicId": null,
   "assuntoLivre": "Demonstração Contábil Consolidada (CPC 36, Lei 6.404, art. 249 e 250)",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 0,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-30~documentacao-de-auditoria-papeis-de-trabalho-1490c7",
   "origem": "tec",
   "data": "2026-07-30",
   "mat": "AUD",
   "topicId": null,
   "assuntoLivre": "Documentação de Auditoria/Papéis de Trabalho",
   "minutos": 9,
   "qResolvidas": 13,
   "qAcertadas": 12,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-30~especies-de-nacionalidade-brasileiros-natos-e-naturalizados-20fccb",
   "origem": "tec",
   "data": "2026-07-30",
   "mat": "DCON",
   "topicId": null,
   "assuntoLivre": "Espécies de Nacionalidade (Brasileiros Natos e Naturalizados)",
   "minutos": 3,
   "qResolvidas": 4,
   "qAcertadas": 2,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-30~goodwill-77fbc0",
   "origem": "tec",
   "data": "2026-07-30",
   "mat": "CG",
   "topicId": null,
   "assuntoLivre": "Goodwill",
   "minutos": 5,
   "qResolvidas": 1,
   "qAcertadas": 0,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-30~jurisprudencia-dos-tribunais-superiores-sobre-controle-da-ad-4cd649",
   "origem": "tec",
   "data": "2026-07-30",
   "mat": "DAD",
   "topicId": null,
   "assuntoLivre": "Jurisprudência dos Tribunais Superiores sobre Controle da Administração Pública",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-30~jurisprudencia-dos-tribunais-superiores-sobre-controle-de-co-110b84",
   "origem": "tec",
   "data": "2026-07-30",
   "mat": "DCON",
   "topicId": null,
   "assuntoLivre": "Jurisprudência dos Tribunais Superiores sobre Controle de Constitucionalidade",
   "minutos": 6,
   "qResolvidas": 4,
   "qAcertadas": 3,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-30~municipios-organizacao-e-competencias-arts-29-a-31-da-cf-198-25e238",
   "origem": "tec",
   "data": "2026-07-30",
   "mat": "DCON",
   "topicId": null,
   "assuntoLivre": "Municípios - Organização e Competências (arts. 29 a 31 da CF/1988)",
   "minutos": 4,
   "qResolvidas": 4,
   "qAcertadas": 3,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-30~perda-da-nacionalidade-093a7b",
   "origem": "tec",
   "data": "2026-07-30",
   "mat": "DCON",
   "topicId": null,
   "assuntoLivre": "Perda da Nacionalidade",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-30~sem-assunto-177bb3",
   "origem": "tec",
   "data": "2026-07-30",
   "mat": "DFin",
   "topicId": null,
   "assuntoLivre": "(sem assunto no TEC)",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 0,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-30~112",
   "origem": "tec",
   "data": "2026-07-30",
   "mat": "DCON",
   "topicId": "112",
   "assuntoLivre": "",
   "minutos": 19,
   "qResolvidas": 5,
   "qAcertadas": 4,
   "obs": "reconstruída do TEC (2 assuntos)"
  },
  {
   "uid": "TEC~2026-07-30~17",
   "origem": "tec",
   "data": "2026-07-30",
   "mat": "DFin",
   "topicId": "17",
   "assuntoLivre": "",
   "minutos": 10,
   "qResolvidas": 9,
   "qAcertadas": 8,
   "obs": "reconstruída do TEC (2 assuntos)"
  },
  {
   "uid": "TEC~2026-07-30~24",
   "origem": "tec",
   "data": "2026-07-30",
   "mat": "DFin",
   "topicId": "24",
   "assuntoLivre": "",
   "minutos": 5,
   "qResolvidas": 6,
   "qAcertadas": 5,
   "obs": "reconstruída do TEC (2 assuntos)"
  },
  {
   "uid": "TEC~2026-07-30~32",
   "origem": "tec",
   "data": "2026-07-30",
   "mat": "CG",
   "topicId": "32",
   "assuntoLivre": "",
   "minutos": 9,
   "qResolvidas": 3,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-30~39",
   "origem": "tec",
   "data": "2026-07-30",
   "mat": "CG",
   "topicId": "39",
   "assuntoLivre": "",
   "minutos": 3,
   "qResolvidas": 2,
   "qAcertadas": 2,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-30~41",
   "origem": "tec",
   "data": "2026-07-30",
   "mat": "CG",
   "topicId": "41",
   "assuntoLivre": "",
   "minutos": 3,
   "qResolvidas": 2,
   "qAcertadas": 2,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-30~80",
   "origem": "tec",
   "data": "2026-07-30",
   "mat": "AUD",
   "topicId": "80",
   "assuntoLivre": "",
   "minutos": 6,
   "qResolvidas": 4,
   "qAcertadas": 3,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-30~81",
   "origem": "tec",
   "data": "2026-07-30",
   "mat": "AUD",
   "topicId": "81",
   "assuntoLivre": "",
   "minutos": 5,
   "qResolvidas": 5,
   "qAcertadas": 4,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-31~investimentos-permanentes-em-coligada-e-empreendimento-contr-9c06d1",
   "origem": "tec",
   "data": "2026-07-31",
   "mat": "DFin",
   "topicId": null,
   "assuntoLivre": "Investimentos Permanentes, em Coligada e Empreendimento Controlado em Conjunto (MCASP e NBC TSP 18)",
   "minutos": 21,
   "qResolvidas": 8,
   "qAcertadas": 7,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-31~lei-n-10-887-2004-aplicacao-da-ec-n-41-2003-9d9e3d",
   "origem": "tec",
   "data": "2026-07-31",
   "mat": "DFin",
   "topicId": null,
   "assuntoLivre": "Lei nº 10.887/2004 -  Aplicação da EC nº 41/2003",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-31~portarias-ministerio-da-previdencia-social-mps-e12fa0",
   "origem": "tec",
   "data": "2026-07-31",
   "mat": "DPREV",
   "topicId": null,
   "assuntoLivre": "Portarias Ministério da Previdência Social (MPS)",
   "minutos": 1,
   "qResolvidas": 5,
   "qAcertadas": 5,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-31~probabilidade-condicional-2a16f5",
   "origem": "tec",
   "data": "2026-07-31",
   "mat": "Estat",
   "topicId": null,
   "assuntoLivre": "Probabilidade Condicional",
   "minutos": 25,
   "qResolvidas": 6,
   "qAcertadas": 6,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-31~regime-proprio-de-previdencia-social-na-constituicao-federal-7b19a3",
   "origem": "tec",
   "data": "2026-07-31",
   "mat": "DFin",
   "topicId": null,
   "assuntoLivre": "Regime Próprio de Previdência Social na Constituição Federal",
   "minutos": 5,
   "qResolvidas": 8,
   "qAcertadas": 7,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-31~regimes-e-metodos-financeiros-e19a49",
   "origem": "tec",
   "data": "2026-07-31",
   "mat": "DPREV",
   "topicId": null,
   "assuntoLivre": "Regimes e Métodos Financeiros",
   "minutos": 4,
   "qResolvidas": 3,
   "qAcertadas": 3,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-31~sem-assunto-177bb3",
   "origem": "tec",
   "data": "2026-07-31",
   "mat": "DFin",
   "topicId": null,
   "assuntoLivre": "(sem assunto no TEC)",
   "minutos": 1,
   "qResolvidas": 2,
   "qAcertadas": 0,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-31~146",
   "origem": "tec",
   "data": "2026-07-31",
   "mat": "PROC",
   "topicId": "146",
   "assuntoLivre": "",
   "minutos": 71,
   "qResolvidas": 26,
   "qAcertadas": 19,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-31~32",
   "origem": "tec",
   "data": "2026-07-31",
   "mat": "CG",
   "topicId": "32",
   "assuntoLivre": "",
   "minutos": 17,
   "qResolvidas": 6,
   "qAcertadas": 5,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-31~4",
   "origem": "tec",
   "data": "2026-07-31",
   "mat": "DFin",
   "topicId": "4",
   "assuntoLivre": "",
   "minutos": 29,
   "qResolvidas": 12,
   "qAcertadas": 11,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-07-31~6",
   "origem": "tec",
   "data": "2026-07-31",
   "mat": "DFin",
   "topicId": "6",
   "assuntoLivre": "",
   "minutos": 30,
   "qResolvidas": 29,
   "qAcertadas": 25,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-08-02~administracao-gerencial-npm-e8078e",
   "origem": "tec",
   "data": "2026-08-02",
   "mat": "DFin",
   "topicId": null,
   "assuntoLivre": "Administração Gerencial / NPM",
   "minutos": 2,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-08-02~governanca-publica-dea0a1",
   "origem": "tec",
   "data": "2026-08-02",
   "mat": "DFin",
   "topicId": null,
   "assuntoLivre": "Governança Pública",
   "minutos": 2,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-08-02~questoes-envolvendo-diversos-assuntos-629606",
   "origem": "tec",
   "data": "2026-08-02",
   "mat": "CIVIL",
   "topicId": null,
   "assuntoLivre": "Questões Envolvendo Diversos Assuntos",
   "minutos": 2,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-08-02~regimes-e-metodos-financeiros-e19a49",
   "origem": "tec",
   "data": "2026-08-02",
   "mat": "DPREV",
   "topicId": null,
   "assuntoLivre": "Regimes e Métodos Financeiros",
   "minutos": 2,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-08-02~riscos-e-incertezas-72f7d8",
   "origem": "tec",
   "data": "2026-08-02",
   "mat": "DPREV",
   "topicId": null,
   "assuntoLivre": "Riscos e incertezas",
   "minutos": 2,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-08-02~sem-assunto-3c157b",
   "origem": "tec",
   "data": "2026-08-02",
   "mat": "PORT",
   "topicId": null,
   "assuntoLivre": "Língua Portuguesa (Português) — geral",
   "minutos": 10,
   "qResolvidas": 6,
   "qAcertadas": 6,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-08-02~1",
   "origem": "tec",
   "data": "2026-08-02",
   "mat": "DFin",
   "topicId": "1",
   "assuntoLivre": "",
   "minutos": 3,
   "qResolvidas": 2,
   "qAcertadas": 2,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-08-02~101",
   "origem": "tec",
   "data": "2026-08-02",
   "mat": "DCON",
   "topicId": "101",
   "assuntoLivre": "",
   "minutos": 3,
   "qResolvidas": 2,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-08-02~102",
   "origem": "tec",
   "data": "2026-08-02",
   "mat": "DCON",
   "topicId": "102",
   "assuntoLivre": "",
   "minutos": 2,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-08-02~106",
   "origem": "tec",
   "data": "2026-08-02",
   "mat": "DCON",
   "topicId": "106",
   "assuntoLivre": "",
   "minutos": 5,
   "qResolvidas": 3,
   "qAcertadas": 3,
   "obs": "reconstruída do TEC (2 assuntos)"
  },
  {
   "uid": "TEC~2026-08-02~108",
   "origem": "tec",
   "data": "2026-08-02",
   "mat": "DCON",
   "topicId": "108",
   "assuntoLivre": "",
   "minutos": 2,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-08-02~113",
   "origem": "tec",
   "data": "2026-08-02",
   "mat": "TI",
   "topicId": "113",
   "assuntoLivre": "",
   "minutos": 3,
   "qResolvidas": 2,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-08-02~115",
   "origem": "tec",
   "data": "2026-08-02",
   "mat": "TI",
   "topicId": "115",
   "assuntoLivre": "",
   "minutos": 3,
   "qResolvidas": 2,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-08-02~118",
   "origem": "tec",
   "data": "2026-08-02",
   "mat": "Estat",
   "topicId": "118",
   "assuntoLivre": "",
   "minutos": 3,
   "qResolvidas": 2,
   "qAcertadas": 2,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-08-02~120",
   "origem": "tec",
   "data": "2026-08-02",
   "mat": "Estat",
   "topicId": "120",
   "assuntoLivre": "",
   "minutos": 2,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-08-02~136",
   "origem": "tec",
   "data": "2026-08-02",
   "mat": "DCON",
   "topicId": "136",
   "assuntoLivre": "",
   "minutos": 3,
   "qResolvidas": 2,
   "qAcertadas": 2,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-08-02~140",
   "origem": "tec",
   "data": "2026-08-02",
   "mat": "CIVIL",
   "topicId": "140",
   "assuntoLivre": "",
   "minutos": 3,
   "qResolvidas": 2,
   "qAcertadas": 2,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-08-02~146",
   "origem": "tec",
   "data": "2026-08-02",
   "mat": "PROC",
   "topicId": "146",
   "assuntoLivre": "",
   "minutos": 2,
   "qResolvidas": 1,
   "qAcertadas": 0,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-08-02~147",
   "origem": "tec",
   "data": "2026-08-02",
   "mat": "PROC",
   "topicId": "147",
   "assuntoLivre": "",
   "minutos": 3,
   "qResolvidas": 2,
   "qAcertadas": 2,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-08-02~2",
   "origem": "tec",
   "data": "2026-08-02",
   "mat": "DFin",
   "topicId": "2",
   "assuntoLivre": "",
   "minutos": 3,
   "qResolvidas": 2,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-08-02~25",
   "origem": "tec",
   "data": "2026-08-02",
   "mat": "CG",
   "topicId": "25",
   "assuntoLivre": "",
   "minutos": 3,
   "qResolvidas": 2,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-08-02~26",
   "origem": "tec",
   "data": "2026-08-02",
   "mat": "CG",
   "topicId": "26",
   "assuntoLivre": "",
   "minutos": 3,
   "qResolvidas": 2,
   "qAcertadas": 2,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-08-02~3",
   "origem": "tec",
   "data": "2026-08-02",
   "mat": "DFin",
   "topicId": "3",
   "assuntoLivre": "",
   "minutos": 3,
   "qResolvidas": 2,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-08-02~4",
   "origem": "tec",
   "data": "2026-08-02",
   "mat": "DFin",
   "topicId": "4",
   "assuntoLivre": "",
   "minutos": 3,
   "qResolvidas": 2,
   "qAcertadas": 2,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-08-02~46",
   "origem": "tec",
   "data": "2026-08-02",
   "mat": "DAD",
   "topicId": "46",
   "assuntoLivre": "",
   "minutos": 7,
   "qResolvidas": 4,
   "qAcertadas": 3,
   "obs": "reconstruída do TEC (2 assuntos)"
  },
  {
   "uid": "TEC~2026-08-02~47",
   "origem": "tec",
   "data": "2026-08-02",
   "mat": "DAD",
   "topicId": "47",
   "assuntoLivre": "",
   "minutos": 3,
   "qResolvidas": 2,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-08-02~48",
   "origem": "tec",
   "data": "2026-08-02",
   "mat": "DAD",
   "topicId": "48",
   "assuntoLivre": "",
   "minutos": 3,
   "qResolvidas": 2,
   "qAcertadas": 2,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-08-02~50",
   "origem": "tec",
   "data": "2026-08-02",
   "mat": "DAD",
   "topicId": "50",
   "assuntoLivre": "",
   "minutos": 5,
   "qResolvidas": 3,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC (2 assuntos)"
  },
  {
   "uid": "TEC~2026-08-02~57",
   "origem": "tec",
   "data": "2026-08-02",
   "mat": "DAD",
   "topicId": "57",
   "assuntoLivre": "",
   "minutos": 3,
   "qResolvidas": 2,
   "qAcertadas": 2,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-08-02~6",
   "origem": "tec",
   "data": "2026-08-02",
   "mat": "DFin",
   "topicId": "6",
   "assuntoLivre": "",
   "minutos": 3,
   "qResolvidas": 2,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-08-02~64",
   "origem": "tec",
   "data": "2026-08-02",
   "mat": "AUD",
   "topicId": "64",
   "assuntoLivre": "",
   "minutos": 3,
   "qResolvidas": 2,
   "qAcertadas": 2,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-08-02~65",
   "origem": "tec",
   "data": "2026-08-02",
   "mat": "AUD",
   "topicId": "65",
   "assuntoLivre": "",
   "minutos": 3,
   "qResolvidas": 2,
   "qAcertadas": 2,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-08-02~67",
   "origem": "tec",
   "data": "2026-08-02",
   "mat": "AUD",
   "topicId": "67",
   "assuntoLivre": "",
   "minutos": 2,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-08-02~69",
   "origem": "tec",
   "data": "2026-08-02",
   "mat": "AUD",
   "topicId": "69",
   "assuntoLivre": "",
   "minutos": 3,
   "qResolvidas": 2,
   "qAcertadas": 0,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-08-02~72",
   "origem": "tec",
   "data": "2026-08-02",
   "mat": "AUD",
   "topicId": "72",
   "assuntoLivre": "",
   "minutos": 2,
   "qResolvidas": 1,
   "qAcertadas": 0,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-08-02~76",
   "origem": "tec",
   "data": "2026-08-02",
   "mat": "AUD",
   "topicId": "76",
   "assuntoLivre": "",
   "minutos": 2,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-08-02~8",
   "origem": "tec",
   "data": "2026-08-02",
   "mat": "DFin",
   "topicId": "8",
   "assuntoLivre": "",
   "minutos": 3,
   "qResolvidas": 2,
   "qAcertadas": 2,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-08-02~83",
   "origem": "tec",
   "data": "2026-08-02",
   "mat": "CASP",
   "topicId": "83",
   "assuntoLivre": "",
   "minutos": 3,
   "qResolvidas": 2,
   "qAcertadas": 2,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-08-02~84",
   "origem": "tec",
   "data": "2026-08-02",
   "mat": "CASP",
   "topicId": "84",
   "assuntoLivre": "",
   "minutos": 3,
   "qResolvidas": 2,
   "qAcertadas": 2,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-08-02~87",
   "origem": "tec",
   "data": "2026-08-02",
   "mat": "CASP",
   "topicId": "87",
   "assuntoLivre": "",
   "minutos": 3,
   "qResolvidas": 2,
   "qAcertadas": 2,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-08-02~88",
   "origem": "tec",
   "data": "2026-08-02",
   "mat": "CASP",
   "topicId": "88",
   "assuntoLivre": "",
   "minutos": 3,
   "qResolvidas": 2,
   "qAcertadas": 2,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-08-02~9",
   "origem": "tec",
   "data": "2026-08-02",
   "mat": "DFin",
   "topicId": "9",
   "assuntoLivre": "",
   "minutos": 3,
   "qResolvidas": 2,
   "qAcertadas": 2,
   "obs": "reconstruída do TEC"
  }
 ]
};
